---
title: "About Me"
---

- __Me:__ I am currently a Master's student studying statistics at the University of Akron. Since my main requirement after the spring semester will be writing my thesis, I am currently searching for a job. I originally wanted to study applied mathematics, however, during my freshman year I took a class on decision trees and logistic regression. This class showed me how powerful and applicable statistics really was. I continued studying mathematics (I even wrote my honors thesis in mathematical biology) but took on statistics and have loved it ever since!


- __Hobbies:__ I enjoy reading history and things relating to financial matters. 

A picture of me (well two years ago at least). 

<embed src="https://docs.google.com/document/d/e/2PACX-1vTikdLFOerVcscSYkGHL4exfo-K0hVN5KgLf1vCk-2esDkk6A_EoxMBKdc9pd5Dx0z_jb0UEHCKgORl/pub?embedded=true" width="800" height="800">



(Note to self: Use following html code to embed pdf into website instead of linking it)

<(embed src="link" width="800" height="800">) (No parentheses)
With large width/height commands to avoid scroll bar